FROM node:14

WORKDIR /root/app/src/

COPY package*.json ./
COPY tsconfig.json ./
COPY client client 
COPY server server

RUN cd client && npm install
RUN npm install

EXPOSE 3000
EXPOSE 5000

CMD ["npm", "run", "dev"]

